-- LUMA Initial Schema
-- Creates the base tables needed for the ATS

-- ============================================
-- Job Postings
-- ============================================
CREATE TABLE IF NOT EXISTS public.job_posting (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  owner text,
  questions json NOT NULL DEFAULT '{"steps":[]}'::json,
  scheduled boolean NOT NULL DEFAULT false,
  metadata json,
  schedule json NOT NULL DEFAULT '{}'::json,
  active_flg boolean NOT NULL DEFAULT true,
  description text,
  org_id bigint
);

-- ============================================
-- Applicants
-- ============================================
CREATE TABLE IF NOT EXISTS public.applicants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  metadata json,
  "recruitInfo" json,
  comments json DEFAULT '{"comments":[]}'::json,
  pass_screen boolean,
  accepted_role boolean,
  job bigint,
  status text NOT NULL DEFAULT 'pending',
  org_id bigint
);

-- ============================================
-- Interviewers
-- ============================================
CREATE TABLE IF NOT EXISTS public.interviewers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text,
  email text NOT NULL,
  metadata json,
  uuid text,
  org_id bigint
);

-- ============================================
-- Interviews
-- ============================================
CREATE TABLE IF NOT EXISTS public.interviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  "startTime" timestamptz,
  "endTime" timestamptz,
  location text,
  type text,
  comments json,
  job bigint,
  applicant text,
  interviewer text,
  org_id bigint
);

-- Enable RLS on all tables
ALTER TABLE public.job_posting ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applicants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interviewers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interviews ENABLE ROW LEVEL SECURITY;
