-- Admin Panel Expansion
-- New tables, RPC functions, and RLS policies for platform admin features

-- ============================================
-- Platform Settings Table (single-row)
-- ============================================
CREATE TABLE IF NOT EXISTS public.platform_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Platform admins can read platform_settings"
  ON platform_settings FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can update platform_settings"
  ON platform_settings FOR UPDATE TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can insert platform_settings"
  ON platform_settings FOR INSERT TO authenticated
  WITH CHECK (is_platform_admin());

-- Insert default row
INSERT INTO platform_settings (settings) VALUES ('{}')
  ON CONFLICT DO NOTHING;

-- ============================================
-- Platform Activity Log
-- ============================================
CREATE TABLE IF NOT EXISTS public.platform_activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  action text NOT NULL,
  actor_id uuid REFERENCES auth.users(id),
  details jsonb DEFAULT '{}'::jsonb
);

ALTER TABLE public.platform_activity_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Platform admins can read activity_log"
  ON platform_activity_log FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can insert activity_log"
  ON platform_activity_log FOR INSERT TO authenticated
  WITH CHECK (is_platform_admin());

-- ============================================
-- RPC: List all auth users (platform admin only)
-- ============================================
CREATE OR REPLACE FUNCTION get_all_users_admin()
RETURNS TABLE (id uuid, email text, created_at timestamptz, last_sign_in_at timestamptz)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT u.id, u.email::text, u.created_at, u.last_sign_in_at
  FROM auth.users u
  WHERE is_platform_admin()
  ORDER BY u.created_at DESC;
$$;

-- ============================================
-- RPC: Add a platform admin by email
-- ============================================
CREATE OR REPLACE FUNCTION add_platform_admin_by_email(target_email text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_user_id uuid;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT id INTO target_user_id FROM auth.users WHERE email = target_email;
  IF target_user_id IS NULL THEN
    RETURN json_build_object('error', 'No user found with that email');
  END IF;

  INSERT INTO platform_admins (user_id) VALUES (target_user_id)
    ON CONFLICT DO NOTHING;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Remove a platform admin
-- ============================================
CREATE OR REPLACE FUNCTION remove_platform_admin(target_user_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  IF target_user_id = auth.uid() THEN
    RETURN json_build_object('error', 'Cannot remove yourself as platform admin');
  END IF;

  DELETE FROM platform_admins WHERE user_id = target_user_id;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Create organization as platform admin
-- ============================================
CREATE OR REPLACE FUNCTION admin_create_organization(
  org_name text,
  org_slug text,
  owner_email text,
  p_color text DEFAULT '#ffc800',
  s_color text DEFAULT '#0F1112'
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  owner_user_id uuid;
  new_org_id bigint;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT id INTO owner_user_id FROM auth.users WHERE email = owner_email;
  IF owner_user_id IS NULL THEN
    RETURN json_build_object('error', 'Owner email not found — user must have an account first');
  END IF;

  -- Check slug uniqueness
  IF EXISTS (SELECT 1 FROM organizations WHERE slug = org_slug) THEN
    RETURN json_build_object('error', 'Slug already in use');
  END IF;

  INSERT INTO organizations (name, slug, owner_id, primary_color, secondary_color)
    VALUES (org_name, org_slug, owner_user_id, p_color, s_color)
    RETURNING id INTO new_org_id;

  INSERT INTO org_members (org_id, user_id, role)
    VALUES (new_org_id, owner_user_id, 'owner');

  RETURN json_build_object('success', true, 'org_id', new_org_id);
END;
$$;

-- ============================================
-- RPC: Delete organization as platform admin
-- ============================================
CREATE OR REPLACE FUNCTION admin_delete_organization(target_org_id bigint)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  org_name_val text;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT name INTO org_name_val FROM organizations WHERE id = target_org_id;
  IF org_name_val IS NULL THEN
    RETURN json_build_object('error', 'Organization not found');
  END IF;

  -- Delete cascades via FK: org_members, job_posting, applicants, interviewers, interviews
  DELETE FROM organizations WHERE id = target_org_id;

  RETURN json_build_object('success', true, 'deleted', org_name_val);
END;
$$;

-- ============================================
-- RPC: Update organization as platform admin
-- ============================================
CREATE OR REPLACE FUNCTION admin_update_organization(
  target_org_id bigint,
  new_name text DEFAULT NULL,
  new_slug text DEFAULT NULL,
  new_primary_color text DEFAULT NULL,
  new_secondary_color text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM organizations WHERE id = target_org_id) THEN
    RETURN json_build_object('error', 'Organization not found');
  END IF;

  -- Check slug uniqueness if changing
  IF new_slug IS NOT NULL AND EXISTS (
    SELECT 1 FROM organizations WHERE slug = new_slug AND id != target_org_id
  ) THEN
    RETURN json_build_object('error', 'Slug already in use');
  END IF;

  UPDATE organizations SET
    name = COALESCE(new_name, name),
    slug = COALESCE(new_slug, slug),
    primary_color = COALESCE(new_primary_color, primary_color),
    secondary_color = COALESCE(new_secondary_color, secondary_color)
  WHERE id = target_org_id;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Transfer organization ownership
-- ============================================
CREATE OR REPLACE FUNCTION admin_transfer_ownership(target_org_id bigint, new_owner_email text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_owner_id uuid;
  old_owner_id uuid;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT id INTO new_owner_id FROM auth.users WHERE email = new_owner_email;
  IF new_owner_id IS NULL THEN
    RETURN json_build_object('error', 'New owner email not found');
  END IF;

  SELECT owner_id INTO old_owner_id FROM organizations WHERE id = target_org_id;
  IF old_owner_id IS NULL THEN
    RETURN json_build_object('error', 'Organization not found');
  END IF;

  -- Update org owner
  UPDATE organizations SET owner_id = new_owner_id WHERE id = target_org_id;

  -- Demote old owner to admin
  UPDATE org_members SET role = 'admin'
    WHERE org_id = target_org_id AND user_id = old_owner_id;

  -- Ensure new owner is a member with owner role
  INSERT INTO org_members (org_id, user_id, role)
    VALUES (target_org_id, new_owner_id, 'owner')
    ON CONFLICT (org_id, user_id) DO UPDATE SET role = 'owner';

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Get all platform admins with email
-- ============================================
CREATE OR REPLACE FUNCTION get_platform_admins()
RETURNS TABLE (id bigint, user_id uuid, email text, created_at timestamptz)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT pa.id, pa.user_id, u.email::text, pa.created_at
  FROM platform_admins pa
  JOIN auth.users u ON u.id = pa.user_id
  WHERE is_platform_admin()
  ORDER BY pa.created_at ASC;
$$;

-- ============================================
-- RPC: Get all job postings cross-org (admin)
-- ============================================
CREATE OR REPLACE FUNCTION get_all_job_postings_admin()
RETURNS TABLE (
  id bigint, created_at timestamptz, name text, description text,
  active_flg boolean, org_id bigint, org_name text, org_slug text,
  applicant_count bigint
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT
    jp.id, jp.created_at, jp.name, jp.description,
    jp.active_flg, jp.org_id,
    o.name AS org_name, o.slug AS org_slug,
    (SELECT count(*) FROM applicants a WHERE a.job = jp.id) AS applicant_count
  FROM job_posting jp
  LEFT JOIN organizations o ON o.id = jp.org_id
  WHERE is_platform_admin()
  ORDER BY jp.created_at DESC;
$$;

-- ============================================
-- RPC: Get user org memberships (admin)
-- ============================================
CREATE OR REPLACE FUNCTION get_user_memberships_admin(target_user_id uuid)
RETURNS TABLE (org_id bigint, org_name text, org_slug text, role org_role)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT om.org_id, o.name AS org_name, o.slug AS org_slug, om.role
  FROM org_members om
  JOIN organizations o ON o.id = om.org_id
  WHERE om.user_id = target_user_id AND is_platform_admin()
  ORDER BY o.name ASC;
$$;

-- ============================================
-- RPC: Admin add user to org by email
-- ============================================
CREATE OR REPLACE FUNCTION admin_add_user_to_org(target_org_id bigint, target_email text, target_role org_role DEFAULT 'recruiter')
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_user_id uuid;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT id INTO target_user_id FROM auth.users WHERE email = target_email;
  IF target_user_id IS NULL THEN
    RETURN json_build_object('error', 'User not found');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM organizations WHERE id = target_org_id) THEN
    RETURN json_build_object('error', 'Organization not found');
  END IF;

  INSERT INTO org_members (org_id, user_id, role)
    VALUES (target_org_id, target_user_id, target_role)
    ON CONFLICT (org_id, user_id) DO UPDATE SET role = target_role;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Admin remove user from org
-- ============================================
CREATE OR REPLACE FUNCTION admin_remove_user_from_org(target_org_id bigint, target_user_id uuid)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  DELETE FROM org_members WHERE org_id = target_org_id AND user_id = target_user_id;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Admin change user role in org
-- ============================================
CREATE OR REPLACE FUNCTION admin_change_user_role(target_org_id bigint, target_user_id uuid, new_role org_role)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  UPDATE org_members SET role = new_role
    WHERE org_id = target_org_id AND user_id = target_user_id;

  IF NOT FOUND THEN
    RETURN json_build_object('error', 'Membership not found');
  END IF;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- Allow platform admins full SELECT on key tables
-- ============================================
CREATE POLICY "Platform admins can read all organizations"
  ON organizations FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can read all org_members"
  ON org_members FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can read all applicants"
  ON applicants FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can read all job_postings"
  ON job_posting FOR SELECT TO authenticated
  USING (is_platform_admin());

CREATE POLICY "Platform admins can read all interviews"
  ON interviews FOR SELECT TO authenticated
  USING (is_platform_admin());

-- ============================================
-- RPC: Get all applicants cross-org (admin)
-- ============================================
CREATE OR REPLACE FUNCTION get_all_applicants_admin()
RETURNS TABLE (
  id bigint, created_at timestamptz, name text, email text,
  status text, job bigint, org_id bigint,
  org_name text, org_slug text, job_name text,
  recruitInfo json
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT
    a.id, a.created_at, a.name, a.email,
    a.status, a.job, a.org_id,
    o.name AS org_name, o.slug AS org_slug,
    jp.name AS job_name,
    a."recruitInfo"
  FROM applicants a
  LEFT JOIN organizations o ON o.id = a.org_id
  LEFT JOIN job_posting jp ON jp.id = a.job
  WHERE is_platform_admin()
  ORDER BY a.created_at DESC;
$$;

-- ============================================
-- RPC: Bulk update applicant status (admin)
-- ============================================
CREATE OR REPLACE FUNCTION admin_bulk_update_applicant_status(applicant_ids bigint[], new_status text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  UPDATE applicants SET status = new_status
    WHERE id = ANY(applicant_ids);

  RETURN json_build_object('success', true, 'updated', array_length(applicant_ids, 1));
END;
$$;

-- ============================================
-- RPC: Bulk delete applicants (admin)
-- ============================================
CREATE OR REPLACE FUNCTION admin_bulk_delete_applicants(applicant_ids bigint[])
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count int;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  DELETE FROM applicants WHERE id = ANY(applicant_ids);
  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  RETURN json_build_object('success', true, 'deleted', deleted_count);
END;
$$;

-- ============================================
-- RPC: Get platform settings
-- ============================================
CREATE OR REPLACE FUNCTION get_platform_settings()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT settings FROM platform_settings LIMIT 1;
$$;

-- ============================================
-- RPC: Update platform settings
-- ============================================
CREATE OR REPLACE FUNCTION update_platform_settings(new_settings jsonb)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  UPDATE platform_settings SET settings = new_settings WHERE id = (SELECT id FROM platform_settings LIMIT 1);

  IF NOT FOUND THEN
    INSERT INTO platform_settings (settings) VALUES (new_settings);
  END IF;

  RETURN json_build_object('success', true);
END;
$$;

-- ============================================
-- RPC: Get admin analytics summary
-- ============================================
CREATE OR REPLACE FUNCTION get_admin_analytics()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  result json;
BEGIN
  IF NOT is_platform_admin() THEN
    RETURN json_build_object('error', 'Not authorized');
  END IF;

  SELECT json_build_object(
    'total_orgs', (SELECT count(*) FROM organizations),
    'total_users', (SELECT count(*) FROM auth.users),
    'total_applicants', (SELECT count(*) FROM applicants),
    'total_interviews', (SELECT count(*) FROM interviews),
    'total_jobs', (SELECT count(*) FROM job_posting),
    'active_jobs', (SELECT count(*) FROM job_posting WHERE active_flg = true),
    'applicants_by_status', (
      SELECT json_object_agg(status, cnt) FROM (
        SELECT status, count(*) as cnt FROM applicants GROUP BY status
      ) s
    ),
    'recent_applicants', (
      SELECT json_agg(row_to_json(r)) FROM (
        SELECT a.id, a.name, a.email, a.created_at, a.status,
               o.name as org_name, jp.name as job_name
        FROM applicants a
        LEFT JOIN organizations o ON o.id = a.org_id
        LEFT JOIN job_posting jp ON jp.id = a.job
        ORDER BY a.created_at DESC LIMIT 10
      ) r
    ),
    'recent_users', (
      SELECT json_agg(row_to_json(r)) FROM (
        SELECT id, email::text, created_at
        FROM auth.users
        ORDER BY created_at DESC LIMIT 10
      ) r
    ),
    'orgs_by_size', (
      SELECT json_agg(row_to_json(r)) FROM (
        SELECT o.id, o.name, o.slug, o.primary_color,
               count(om.id) as member_count
        FROM organizations o
        LEFT JOIN org_members om ON om.org_id = o.id
        GROUP BY o.id, o.name, o.slug, o.primary_color
        ORDER BY member_count DESC
      ) r
    ),
    'applicants_last_30_days', (
      SELECT json_agg(row_to_json(r)) FROM (
        SELECT date_trunc('day', created_at)::date as day, count(*) as count
        FROM applicants
        WHERE created_at >= now() - interval '30 days'
        GROUP BY day
        ORDER BY day ASC
      ) r
    )
  ) INTO result;

  RETURN result;
END;
$$;

-- ============================================
-- RPC: Check maintenance mode (public, no auth)
-- ============================================
CREATE OR REPLACE FUNCTION is_maintenance_mode()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT COALESCE((settings->>'maintenance_mode')::boolean, false)
  FROM platform_settings LIMIT 1;
$$;
