-- Multi-Tenancy: Organizations + Members
-- Creates org infrastructure and links existing tables

-- ============================================
-- Org Role Enum
-- ============================================
DO $$ BEGIN
  CREATE TYPE org_role AS ENUM ('owner', 'admin', 'recruiter', 'viewer');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- Organizations Table
-- ============================================
CREATE TABLE IF NOT EXISTS public.organizations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  primary_color text NOT NULL DEFAULT '#ffc800',
  secondary_color text NOT NULL DEFAULT '#0F1112',
  settings json NOT NULL DEFAULT '{}'::json,
  owner_id uuid NOT NULL REFERENCES auth.users(id)
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

-- ============================================
-- Org Members Table
-- ============================================
CREATE TABLE IF NOT EXISTS public.org_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role org_role NOT NULL DEFAULT 'viewer',
  UNIQUE(org_id, user_id)
);

ALTER TABLE public.org_members ENABLE ROW LEVEL SECURITY;

-- ============================================
-- Add org_id foreign keys to existing tables
-- ============================================
DO $$ BEGIN
  ALTER TABLE public.job_posting
    ADD CONSTRAINT job_posting_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.applicants
    ADD CONSTRAINT applicants_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.interviewers
    ADD CONSTRAINT interviewers_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.interviews
    ADD CONSTRAINT interviews_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- Indexes
-- ============================================
CREATE INDEX IF NOT EXISTS idx_org_members_org_id ON public.org_members(org_id);
CREATE INDEX IF NOT EXISTS idx_org_members_user_id ON public.org_members(user_id);
CREATE INDEX IF NOT EXISTS idx_job_posting_org_id ON public.job_posting(org_id);
CREATE INDEX IF NOT EXISTS idx_applicants_org_id ON public.applicants(org_id);
CREATE INDEX IF NOT EXISTS idx_interviewers_org_id ON public.interviewers(org_id);
CREATE INDEX IF NOT EXISTS idx_interviews_org_id ON public.interviews(org_id);
CREATE INDEX IF NOT EXISTS idx_organizations_slug ON public.organizations(slug);
