-- Scheduling config table (per-org or per-job scheduling preferences)
CREATE TABLE public.scheduling_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  job_id bigint REFERENCES job_posting(id) ON DELETE CASCADE,
  algorithm_id text NOT NULL DEFAULT 'greedy-first-available',
  config jsonb NOT NULL DEFAULT '{}',
  last_run_at timestamptz,
  last_run_result jsonb,
  UNIQUE (org_id, job_id)
);

-- Interviewer availability table
CREATE TABLE public.interviewer_availability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  timezone text NOT NULL DEFAULT 'America/New_York',
  UNIQUE (org_id, user_id, date, start_time)
);

-- Add source column to interviews to track manual vs auto-scheduled
ALTER TABLE public.interviews
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'manual';

-- RLS for scheduling_config
ALTER TABLE public.scheduling_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Platform admins can manage scheduling_config"
  ON public.scheduling_config FOR ALL
  USING (public.is_platform_admin());

CREATE POLICY "Org members can view scheduling_config"
  ON public.scheduling_config FOR SELECT
  USING (public.is_org_member(org_id));

-- RLS for interviewer_availability
ALTER TABLE public.interviewer_availability ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own availability"
  ON public.interviewer_availability FOR ALL
  USING (auth.uid() = user_id);

CREATE POLICY "Org members can view interviewer availability"
  ON public.interviewer_availability FOR SELECT
  USING (public.is_org_member(org_id));

CREATE POLICY "Platform admins can manage all interviewer availability"
  ON public.interviewer_availability FOR ALL
  USING (public.is_platform_admin());

-- Indexes
CREATE INDEX idx_scheduling_config_org ON public.scheduling_config(org_id);
CREATE INDEX idx_interviewer_availability_org ON public.interviewer_availability(org_id);
CREATE INDEX idx_interviewer_availability_user ON public.interviewer_availability(user_id);
CREATE INDEX idx_interviews_source ON public.interviews(source);
