-- V1: Save-and-resume for in-progress applications
-- Drafts are addressed by an opaque magic_token sent to the applicant via
-- email. They are public-writeable when accompanied by a valid token; this
-- replaces the localStorage-only persistence of the existing flow.

CREATE TABLE IF NOT EXISTS public.application_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.job_posting(id) ON DELETE CASCADE,
  email text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  selected_team_slugs text[] NOT NULL DEFAULT ARRAY[]::text[],
  magic_token text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL DEFAULT now() + interval '14 days',
  submitted_at timestamptz,
  UNIQUE (job_id, email)
);

CREATE INDEX IF NOT EXISTS idx_application_drafts_org_id ON public.application_drafts(org_id);
CREATE INDEX IF NOT EXISTS idx_application_drafts_token ON public.application_drafts(magic_token);
CREATE INDEX IF NOT EXISTS idx_application_drafts_expires_at ON public.application_drafts(expires_at);

ALTER TABLE public.application_drafts ENABLE ROW LEVEL SECURITY;

-- Public can insert (a draft) and select/update their own draft only by
-- presenting the magic_token. Anon clients pass the token as a request
-- header / query param; the policy compares it against the row's token.
-- Note: tokens must be unguessable (≥128 bits of entropy) — enforced in
-- the API layer that generates them.
--
-- For SELECT/UPDATE we cannot filter by header from RLS directly, so the
-- API does the lookup with a service-role client. Public RLS therefore
-- only opens INSERT here; reads/writes go through server endpoints.

DO $$ BEGIN
  CREATE POLICY drafts_insert_public ON public.application_drafts
    FOR INSERT WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Org admins can see all drafts for jobs in their org (for support).
DO $$ BEGIN
  CREATE POLICY drafts_select_admin ON public.application_drafts
    FOR SELECT USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Keep updated_at fresh.
CREATE OR REPLACE FUNCTION public.touch_application_drafts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DO $$ BEGIN
  CREATE TRIGGER application_drafts_touch_updated_at
    BEFORE UPDATE ON public.application_drafts
    FOR EACH ROW EXECUTE FUNCTION public.touch_application_drafts_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
