-- V1: Per-team hire/reject/waitlist decisions
-- One row per (applicant, team). If 2+ teams hire the same applicant, the
-- dashboard surfaces a conflict (computed at read time, not stored).

DO $$ BEGIN
  CREATE TYPE decision_outcome AS ENUM ('hire', 'reject', 'waitlist');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  applicant_id bigint NOT NULL REFERENCES public.applicants(id) ON DELETE CASCADE,
  team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  outcome decision_outcome NOT NULL,
  decided_by uuid NOT NULL REFERENCES auth.users(id),
  decided_at timestamptz NOT NULL DEFAULT now(),
  email_sent_at timestamptz,
  notes text,
  UNIQUE (applicant_id, team_id)
);

CREATE INDEX IF NOT EXISTS idx_decisions_org_id ON public.decisions(org_id);
CREATE INDEX IF NOT EXISTS idx_decisions_applicant_id ON public.decisions(applicant_id);
CREATE INDEX IF NOT EXISTS idx_decisions_team_id ON public.decisions(team_id);

ALTER TABLE public.decisions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY decisions_select_org ON public.decisions
    FOR SELECT USING (is_org_member(org_id));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Advisors and admins can write decisions. Use has_app_role to include the
-- new advisor role; admins are always allowed via has_org_role.
DO $$ BEGIN
  CREATE POLICY decisions_insert_advisor ON public.decisions
    FOR INSERT WITH CHECK (
      has_org_role(org_id, 'admin') OR has_app_role(org_id, 'advisor')
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY decisions_update_advisor ON public.decisions
    FOR UPDATE USING (
      has_org_role(org_id, 'admin') OR has_app_role(org_id, 'advisor')
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY decisions_delete_admin ON public.decisions
    FOR DELETE USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
