-- V1: Per-org Teams
-- Generalizes the "subteam" concept (Infinitum, Astra, Terra, Juvo for
-- Archimedes, but any org can define its own set).

CREATE TABLE IF NOT EXISTS public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  display_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  UNIQUE (org_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_teams_org_id ON public.teams(org_id);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- Anyone in the org can read teams; admins+ can write.
DO $$ BEGIN
  CREATE POLICY teams_select_org_members ON public.teams
    FOR SELECT USING (is_org_member(org_id));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY teams_select_public ON public.teams
    FOR SELECT USING (active = true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY teams_insert_admin ON public.teams
    FOR INSERT WITH CHECK (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY teams_update_admin ON public.teams
    FOR UPDATE USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY teams_delete_admin ON public.teams
    FOR DELETE USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Seed Archimedes' four teams when the Archimedes org exists.
-- Safe to re-run: ON CONFLICT skips existing slugs.
INSERT INTO public.teams (org_id, name, slug, description, display_order)
SELECT o.id, t.name, t.slug, t.description, t.display_order
FROM public.organizations o
CROSS JOIN (VALUES
  ('Infinitum',  'infinitum', 'Infinitum subteam', 1),
  ('Astra',      'astra',     'Astra subteam',     2),
  ('Terra',      'terra',     'Terra subteam',     3),
  ('Juvo',       'juvo',      'Juvo subteam',      4)
) AS t(name, slug, description, display_order)
WHERE o.slug = 'archimedes'
ON CONFLICT (org_id, slug) DO NOTHING;
