-- V1: Reviewer pool per job
-- A fixed set of reviewers is assigned per job posting. Reviewers vote
-- approve/reject; thresholds for auto-advance/auto-deny are read from
-- org_settings.review_thresholds.
--
-- Expected org_settings shape (informational; see src/lib/types/orgSettings.ts):
--   {
--     "review_thresholds": {
--       "approve_to_advance": 3,
--       "reject_to_deny": 2,
--       "blinded_review": true,
--       "weighted_scoring": false
--     }
--   }

CREATE TABLE IF NOT EXISTS public.job_reviewers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.job_posting(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  weight numeric NOT NULL DEFAULT 1.0,
  UNIQUE (job_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_job_reviewers_org_id ON public.job_reviewers(org_id);
CREATE INDEX IF NOT EXISTS idx_job_reviewers_job_id ON public.job_reviewers(job_id);
CREATE INDEX IF NOT EXISTS idx_job_reviewers_user_id ON public.job_reviewers(user_id);

ALTER TABLE public.job_reviewers ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY job_reviewers_select_org ON public.job_reviewers
    FOR SELECT USING (is_org_member(org_id));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY job_reviewers_insert_admin ON public.job_reviewers
    FOR INSERT WITH CHECK (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY job_reviewers_delete_admin ON public.job_reviewers
    FOR DELETE USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY job_reviewers_update_admin ON public.job_reviewers
    FOR UPDATE USING (has_org_role(org_id, 'admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Seed sensible defaults for any org whose settings don't yet carry
-- review_thresholds. Non-destructive: only fills in missing keys.
UPDATE public.organizations
SET settings = settings::jsonb || jsonb_build_object(
  'review_thresholds', jsonb_build_object(
    'approve_to_advance', 3,
    'reject_to_deny', 2,
    'blinded_review', true,
    'weighted_scoring', false
  )
)
WHERE NOT (settings::jsonb ? 'review_thresholds');
