-- Hand off or swap an interview, with the other person's consent.
--
-- Recruiters drop out. Until now the only fix was an admin editing rows, so in
-- practice people just swapped verbally and the schedule went stale — the app
-- said one person was interviewing while somebody else actually turned up, and
-- the evaluation landed on the wrong row.
--
-- A transfer is therefore a REQUEST, not an edit. Nothing moves until the
-- recipient accepts. Two shapes:
--
--   handoff — "please take my interview"
--   swap    — "take mine, I'll take yours" (both interviews move together)
--
-- Everything goes through SECURITY DEFINER functions rather than table writes:
-- accepting has to update an `interviews` row the recipient does not own, which
-- RLS correctly forbids, and the swap must move both rows or neither.

CREATE TYPE public.transfer_kind   AS ENUM ('handoff', 'swap');
CREATE TYPE public.transfer_status AS ENUM ('pending', 'accepted', 'declined', 'cancelled');

CREATE TABLE public.interview_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  -- The interview being given away.
  interview_id bigint NOT NULL REFERENCES public.interviews(id) ON DELETE CASCADE,
  -- For a swap, what the requester takes in return. NULL for a handoff.
  counterpart_interview_id bigint REFERENCES public.interviews(id) ON DELETE CASCADE,
  kind public.transfer_kind NOT NULL,
  from_email text NOT NULL,
  to_email text NOT NULL,
  status public.transfer_status NOT NULL DEFAULT 'pending',
  note text,
  responded_at timestamptz,
  CONSTRAINT swap_needs_counterpart
    CHECK ((kind = 'swap') = (counterpart_interview_id IS NOT NULL)),
  CONSTRAINT not_to_self CHECK (lower(from_email) <> lower(to_email))
);

-- One live request per interview, so two people can't both be promised it.
CREATE UNIQUE INDEX interview_transfers_one_pending
  ON public.interview_transfers (interview_id) WHERE status = 'pending';

CREATE INDEX idx_interview_transfers_to ON public.interview_transfers (org_id, to_email, status);
CREATE INDEX idx_interview_transfers_from ON public.interview_transfers (org_id, from_email, status);

ALTER TABLE public.interview_transfers ENABLE ROW LEVEL SECURITY;

-- Readable by the two people involved, and by org admins who may have to
-- untangle it. Writes go through the functions below, never directly.
-- Read the caller's address from the JWT, NOT from auth.users: `authenticated`
-- has no SELECT on that table, so a policy that queries it errors instead of
-- filtering and the whole table becomes unreadable. The SECURITY DEFINER
-- functions below hide the problem, because they run as the owner.
CREATE POLICY "Participants and admins can read transfers"
  ON public.interview_transfers FOR SELECT
  USING (
    public.is_org_member(org_id) AND (
      lower(from_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      OR lower(to_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      OR public.has_org_role(org_id, 'admin')
    )
  );

-- ── Request ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.request_interview_transfer(
  target_interview_id bigint,
  recipient_email text,
  transfer_kind public.transfer_kind DEFAULT 'handoff',
  offered_interview_id bigint DEFAULT NULL,
  transfer_note text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  me text;
  iv public.interviews%ROWTYPE;
  counterpart public.interviews%ROWTYPE;
  new_id bigint;
BEGIN
  SELECT email INTO me FROM auth.users WHERE id = auth.uid();
  IF me IS NULL THEN RETURN json_build_object('error', 'Not authenticated'); END IF;

  SELECT * INTO iv FROM public.interviews WHERE id = target_interview_id;
  IF iv.id IS NULL THEN RETURN json_build_object('error', 'Interview not found'); END IF;
  IF lower(iv.interviewer) <> lower(me) THEN
    RETURN json_build_object('error', 'That interview is not yours to hand off');
  END IF;
  IF NOT public.is_org_member(iv.org_id) THEN
    RETURN json_build_object('error', 'Not a member of this organization');
  END IF;
  IF lower(recipient_email) = lower(me) THEN
    RETURN json_build_object('error', 'You cannot transfer an interview to yourself');
  END IF;

  -- The recipient must actually be on the team.
  IF NOT EXISTS (
    SELECT 1 FROM public.org_members m JOIN auth.users u ON u.id = m.user_id
    WHERE m.org_id = iv.org_id AND lower(u.email) = lower(recipient_email)
  ) THEN
    RETURN json_build_object('error', 'That person is not a member of this organization');
  END IF;

  -- Already staffing this very session: accepting would make them appear twice.
  IF EXISTS (
    SELECT 1 FROM public.interviews x
    WHERE x.location = iv.location AND x.start_time = iv.start_time
      AND x.org_id = iv.org_id AND lower(x.interviewer) = lower(recipient_email)
  ) THEN
    RETURN json_build_object('error', 'They are already interviewing in that session');
  END IF;

  IF EXISTS (SELECT 1 FROM public.interview_transfers t
             WHERE t.interview_id = target_interview_id AND t.status = 'pending') THEN
    RETURN json_build_object('error', 'There is already a pending request for this interview');
  END IF;

  IF transfer_kind = 'swap' THEN
    SELECT * INTO counterpart FROM public.interviews WHERE id = offered_interview_id;
    IF counterpart.id IS NULL THEN RETURN json_build_object('error', 'Swap target not found'); END IF;
    IF lower(counterpart.interviewer) <> lower(recipient_email) THEN
      RETURN json_build_object('error', 'The swap target does not belong to that person');
    END IF;
    IF counterpart.org_id <> iv.org_id THEN
      RETURN json_build_object('error', 'Cannot swap across organizations');
    END IF;
  END IF;

  INSERT INTO public.interview_transfers
    (org_id, interview_id, counterpart_interview_id, kind, from_email, to_email, note)
  VALUES (iv.org_id, target_interview_id,
          CASE WHEN transfer_kind = 'swap' THEN offered_interview_id END,
          transfer_kind, me, recipient_email, transfer_note)
  RETURNING id INTO new_id;

  RETURN json_build_object('id', new_id, 'status', 'pending');
END;
$$;

-- ── Respond ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.respond_to_interview_transfer(
  transfer_id bigint,
  accept boolean
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  me text;
  t public.interview_transfers%ROWTYPE;
  iv public.interviews%ROWTYPE;
  counterpart public.interviews%ROWTYPE;
BEGIN
  SELECT email INTO me FROM auth.users WHERE id = auth.uid();
  IF me IS NULL THEN RETURN json_build_object('error', 'Not authenticated'); END IF;

  SELECT * INTO t FROM public.interview_transfers WHERE id = transfer_id FOR UPDATE;
  IF t.id IS NULL THEN RETURN json_build_object('error', 'Request not found'); END IF;
  IF t.status <> 'pending' THEN
    RETURN json_build_object('error', 'That request has already been ' || t.status);
  END IF;
  IF lower(t.to_email) <> lower(me) THEN
    RETURN json_build_object('error', 'That request was not sent to you');
  END IF;

  IF NOT accept THEN
    UPDATE public.interview_transfers
       SET status = 'declined', responded_at = now() WHERE id = transfer_id;
    RETURN json_build_object('status', 'declined');
  END IF;

  SELECT * INTO iv FROM public.interviews WHERE id = t.interview_id;
  IF iv.id IS NULL THEN
    UPDATE public.interview_transfers SET status = 'cancelled', responded_at = now() WHERE id = transfer_id;
    RETURN json_build_object('error', 'That interview no longer exists');
  END IF;

  -- Re-check the clash at ACCEPT time, not just at request time: the recipient's
  -- schedule can change between asking and answering.
  IF EXISTS (
    SELECT 1 FROM public.interviews x
    WHERE x.org_id = iv.org_id AND lower(x.interviewer) = lower(me)
      AND x.id <> iv.id
      AND NOT (t.kind = 'swap' AND x.id = t.counterpart_interview_id)
      AND x.start_time < iv.end_time AND x.end_time > iv.start_time
  ) THEN
    RETURN json_build_object('error', 'You already have an interview at that time');
  END IF;

  IF t.kind = 'swap' THEN
    SELECT * INTO counterpart FROM public.interviews WHERE id = t.counterpart_interview_id;
    IF counterpart.id IS NULL THEN
      UPDATE public.interview_transfers SET status = 'cancelled', responded_at = now() WHERE id = transfer_id;
      RETURN json_build_object('error', 'The interview you offered no longer exists');
    END IF;
    IF lower(counterpart.interviewer) <> lower(me) THEN
      RETURN json_build_object('error', 'The interview you offered is no longer yours');
    END IF;
    -- The requester must be free for what they are taking back.
    IF EXISTS (
      SELECT 1 FROM public.interviews x
      WHERE x.org_id = iv.org_id AND lower(x.interviewer) = lower(t.from_email)
        AND x.id <> iv.id AND x.id <> counterpart.id
        AND x.start_time < counterpart.end_time AND x.end_time > counterpart.start_time
    ) THEN
      RETURN json_build_object('error', 'They already have an interview at that time');
    END IF;

    UPDATE public.interviews SET interviewer = t.from_email WHERE id = counterpart.id;
  END IF;

  UPDATE public.interviews SET interviewer = t.to_email WHERE id = iv.id;
  UPDATE public.interview_transfers
     SET status = 'accepted', responded_at = now() WHERE id = transfer_id;

  RETURN json_build_object('status', 'accepted', 'kind', t.kind);
END;
$$;

-- ── Cancel (requester withdraws) ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.cancel_interview_transfer(transfer_id bigint)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE me text; t public.interview_transfers%ROWTYPE;
BEGIN
  SELECT email INTO me FROM auth.users WHERE id = auth.uid();
  SELECT * INTO t FROM public.interview_transfers WHERE id = transfer_id;
  IF t.id IS NULL THEN RETURN json_build_object('error', 'Request not found'); END IF;
  IF lower(t.from_email) <> lower(me) THEN
    RETURN json_build_object('error', 'That request is not yours to cancel');
  END IF;
  IF t.status <> 'pending' THEN
    RETURN json_build_object('error', 'That request has already been ' || t.status);
  END IF;
  UPDATE public.interview_transfers
     SET status = 'cancelled', responded_at = now() WHERE id = transfer_id;
  RETURN json_build_object('status', 'cancelled');
END;
$$;

-- Supabase grants EXECUTE to PUBLIC on new functions; revoke and re-grant
-- narrowly (migration 00022 is the worked example).
REVOKE ALL ON FUNCTION public.request_interview_transfer(bigint, text, public.transfer_kind, bigint, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.respond_to_interview_transfer(bigint, boolean) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.cancel_interview_transfer(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.request_interview_transfer(bigint, text, public.transfer_kind, bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.respond_to_interview_transfer(bigint, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_interview_transfer(bigint) TO authenticated;

-- The table itself is read-only to clients.
REVOKE INSERT, UPDATE, DELETE ON public.interview_transfers FROM anon, authenticated;
