-- Round 2 selection: per-team "second interview" picks and readiness scores.
--
-- After the first interview round each team builds its second-interview list
-- from a ranking of the applications that put it first. Two new records:
--
--   second_round_picks — "this application gets a second interview". An
--     application is already one team's application (00024), so a pick is
--     simply the application id; there is no separate team column to drift.
--     No cap per team: the only hard numbers are the final team sizes.
--
--   readiness_scores — every recruiter's 1-10 "ready for round 2?" rating of an
--     application, given twice: once WITHOUT seeing interview scores ('blind')
--     and once WITH them ('informed'). One row per (application, rater, pass),
--     so re-rating replaces rather than stacks.
--
-- Neither changes `applicants.status`: status still means round 1's outcome, and
-- a pick is a working list the teams edit up until decision emails go out.
--
-- Reads are open to any org member, because the ranking shows everyone's
-- aggregate. Writes need recruiter or above; readiness rows are further limited
-- to the rater's own. `rater_email`/`picked_by_email` come from the JWT, never
-- from auth.users — `authenticated` cannot read that table (see 00036).

CREATE TABLE public.second_round_picks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  applicant_id bigint NOT NULL UNIQUE REFERENCES public.applicants(id) ON DELETE CASCADE,
  picked_by uuid NOT NULL DEFAULT auth.uid(),
  picked_by_email text NOT NULL DEFAULT lower(coalesce(auth.jwt() ->> 'email', ''))
);

CREATE INDEX idx_second_round_picks_org ON public.second_round_picks (org_id);

CREATE TABLE public.readiness_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  applicant_id bigint NOT NULL REFERENCES public.applicants(id) ON DELETE CASCADE,
  rater_id uuid NOT NULL DEFAULT auth.uid(),
  rater_email text NOT NULL DEFAULT lower(coalesce(auth.jwt() ->> 'email', '')),
  pass text NOT NULL CHECK (pass IN ('blind', 'informed')),
  score smallint NOT NULL CHECK (score BETWEEN 1 AND 10),
  UNIQUE (applicant_id, rater_id, pass)
);

CREATE INDEX idx_readiness_scores_org ON public.readiness_scores (org_id);

ALTER TABLE public.second_round_picks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.readiness_scores ENABLE ROW LEVEL SECURITY;

-- The application must belong to the org the row claims, or a recruiter in one
-- org could attach rows to another org's applicants.
CREATE OR REPLACE FUNCTION public.applicant_in_org(check_applicant_id bigint, check_org_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.applicants WHERE id = check_applicant_id AND org_id = check_org_id
  );
$$;

CREATE POLICY second_round_picks_select ON public.second_round_picks
  FOR SELECT USING (public.is_org_member(org_id));

CREATE POLICY second_round_picks_insert ON public.second_round_picks
  FOR INSERT WITH CHECK (
    public.has_org_role(org_id, 'recruiter')
    AND public.applicant_in_org(applicant_id, org_id)
    AND picked_by = auth.uid()
  );

CREATE POLICY second_round_picks_delete ON public.second_round_picks
  FOR DELETE USING (public.has_org_role(org_id, 'recruiter'));

CREATE POLICY readiness_scores_select ON public.readiness_scores
  FOR SELECT USING (public.is_org_member(org_id));

CREATE POLICY readiness_scores_insert ON public.readiness_scores
  FOR INSERT WITH CHECK (
    public.has_org_role(org_id, 'recruiter')
    AND public.applicant_in_org(applicant_id, org_id)
    AND rater_id = auth.uid()
    AND rater_email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

CREATE POLICY readiness_scores_update ON public.readiness_scores
  FOR UPDATE
  USING (rater_id = auth.uid() AND public.has_org_role(org_id, 'recruiter'))
  WITH CHECK (
    rater_id = auth.uid()
    AND public.applicant_in_org(applicant_id, org_id)
    AND rater_email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );

CREATE POLICY readiness_scores_delete ON public.readiness_scores
  FOR DELETE USING (rater_id = auth.uid());

-- Supabase grants new public tables full CRUD to anon; nothing anonymous
-- belongs here (see 00022).
REVOKE ALL ON public.second_round_picks FROM anon;
REVOKE ALL ON public.readiness_scores FROM anon;
REVOKE UPDATE ON public.second_round_picks FROM authenticated;
REVOKE ALL ON FUNCTION public.applicant_in_org(bigint, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.applicant_in_org(bigint, bigint) TO authenticated;
